language: node_js
node_js:
  - 0.8
script: "npm run-script ci"
env:
  global:
    - SELENIUM_HOST=ondemand.saucelabs.com
    - SELENIUM_PORT=80
    - secure: "Se5f0bGTUXVo7BRUfxzbV3Df1zhJPc4NsYwueRHSqFUklUB9AHhIT79U/rk0\nqJeDkCLqF1t5CDSHy6wVl94JXk/+iW3JXCjaSKuGZGw94RRKe9DgC4E1g1IP\nEnucgi4o8XfvlvR/cZYqH5aTGh+Sw7MK5XMUkB5YeafSaVmEXVE="
