---
language: node_js
node_js:
- '0.10'
- '0.8'
- '0.6'
script: npm run-script ci
env:
  global:
  - BUSTER_TEST_OPT="--reporter specification"
  - SAUCE_USERNAME=cujojs-msgs
  - secure: "MYxtFRyIHuXxwWAy5TafzNK06+AdLfEXv+UqnLP29VWZATw6EDP5Tmx2b6Yx\nSdxOsYtSaghP3M/vBwVEaOHeV7lJ4qoAMJhDoZyr0j/Xel4agVPA2rlOOeNe\n0kRTM8a7LMdB+fFf03rjKWc8BF8AuV+YDDOZLkLPmyErre6pxK0="
